### PR TITLE
Missing "get-type" method for encrypted links resource

### PR DESCRIPTION
**Pull request by tewfik-ghariani**
Without it, "info" command fails with the following

```Traceback (most recent call last):
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/bin/nixops", line 8, in <module>
    sys.exit(main())
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/__main__.py", line 710, in main
    args.op(args)
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/script_defs.py", line 338, in op_info
    do_eval(depl)
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/script_defs.py", line 246, in do_eval
    depl.evaluate()
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/deployment.py", line 565, in evaluate
    defn = _create_definition(name, cfg, cfg["targetEnv"])
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/deployment.py", line 1796, in _create_definition
    if type_name == cls.get_resource_type():
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/resources/__init__.py", line 41, in get_resource_type
    return cls.get_type()
  File "/home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/resources/__init__.py", line 36, in get_type
    raise NotImplementedError("get_type")
NotImplementedError: get_type
> /home/tewfikghariani/.cache/pypoetry/virtualenvs/nixops-xSH9JnDb-py3.8/lib/python3.8/site-packages/nixops/resources/__init__.py(36)get_type()
-> raise NotImplementedError("get_type")
(Pdb) cls
<class 'nixops_encrypted_links.lib.EncryptedLinksDefinition'>
```

cc  @adisbladis 

+ re-locking poetry

### CODE REVIEW

**Comment by tewfik-ghariani** [comment]
FYI @AmineChikhaoui

**Comment by tewfik-ghariani** [comment]
@adisbladis  can we get this merged please? ^^

**Comment by johnalotoski** [comment]
This is also causing other plugins to fail with other nixops commands (deploy, etc) for the same reason when multiple plugins are packaged into the same nixops, so I'm also looking forward to this improvement and confirm it fixes this particular issue.

**Comment by johnalotoski** [comment]
I'll open a separate issue for another problem this plugin has with others. I'm not sure yet what needs to be corrected (this repo or the other plugin).

**Comment by AmineChikhaoui** [comment]
Thanks @tewfik-ghariani

**Pull request merged**
